USE TestMRecords
TRUNCATE TABLE Actors;
TRUNCATE TABLE Games;
TRUNCATE TABLE Players;
TRUNCATE TABLE Rolesets;
TRUNCATE TABLE Votes;
TRUNCATE TABLE Kills;
TRUNCATE TABLE Guilts;
TRUNCATE TABLE Targets;
TRUNCATE TABLE MTargets;
TRUNCATE TABLE Reveals;

