USE TestMRecords;

CREATE TABLE Players(
p_id INT UNSIGNED NOT NULL,
name VARCHAR(50),
PRIMARY KEY (p_id));

CREATE TABLE Rolesets(
roleset_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
nTOWN SMALLINT UNSIGNED NOT NULL DEFAULT 0,
nCOP SMALLINT UNSIGNED NOT NULL DEFAULT 0,
nDOCTOR SMALLINT UNSIGNED NOT NULL DEFAULT 0,
nCELEB SMALLINT UNSIGNED NOT NULL DEFAULT 0,
nMILKY SMALLINT UNSIGNED NOT NULL DEFAULT 0,
nMILLER SMALLINT UNSIGNED NOT NULL DEFAULT 0,
ntTown SMALLINT UNSIGNED AS (nTOWN+nCOP+nDOCTOR+nCELEB+nMILKY+nMILLER),
nMAFIA SMALLINT UNSIGNED NOT NULL DEFAULT 0,
nGODFATHER SMALLINT UNSIGNED NOT NULL DEFAULT 0,
nSTRIPPER SMALLINT UNSIGNED NOT NULL DEFAULT 0,
ntMafia SMALLINT UNSIGNED AS (nMAFIA+nGODFATHER+nSTRIPPER),
nIDIOT SMALLINT UNSIGNED NOT NULL DEFAULT 0,
ntRogue SMALLINT UNSIGNED AS (nIDIOT),
nPlayers SMALLINT UNSIGNED AS (nTOWN+nCOP+nDOCTOR+nCELEB+nMILKY+nMILLER+nMAFIA+nGODFATHER+nSTRIPPER+nIDIOT),
PRIMARY KEY (roleset_id) );

CREATE TABLE Games(
g_id INT UNSIGNED NOT NULL,
winner CHAR(5),
end_phase CHAR(5),
end_day SMALLINT UNSIGNED,
datetime DATETIME,
end_datetime DATETIME,
roleset_id INT UNSIGNED,
PRIMARY KEY (g_id) );

CREATE TABLE Actors(
g_id INT UNSIGNED NOT NULL,
p_id INT UNSIGNED NOT NULL,
role CHAR(10) NOT NULL,
PRIMARY KEY (g_id,p_id) );

CREATE TABLE Votes(
v_id SMALLINT UNSIGNED NOT NULL,
g_id INT UNSIGNED NOT NULL,
p_id1 INT UNSIGNED NOT NULL,
p_id2 INT UNSIGNED,
day SMALLINT UNSIGNED,
datetime DATETIME,
PRIMARY KEY (v_id, g_id) );

CREATE TABLE Targets(
g_id INT UNSIGNED NOT NULL,
p_id1 INT UNSIGNED NOT NULL,
p_id2 INT UNSIGNED,
night SMALLINT UNSIGNED NOT NULL,
datetime DATETIME,
PRIMARY KEY (g_id, p_id1, night) );

CREATE TABLE MTargets(
g_id INT UNSIGNED NOT NULL,
p_id1 INT UNSIGNED,
p_id2 INT UNSIGNED,
night SMALLINT UNSIGNED NOT NULL,
datetime DATETIME,
PRIMARY KEY (g_id, night) );

CREATE TABLE Reveals(
g_id INT UNSIGNED NOT NULL,
p_id INT UNSIGNED NOT NULL,
day SMALLINT UNSIGNED NOT NULL,
distracted BIT NOT NULL,
datetime DATETIME,
PRIMARY KEY (g_id, p_id, day) );

CREATE TABLE Kills(
kill_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
g_id INT UNSIGNED NOT NULL,
kill_type CHAR(10),
p_id INT UNSIGNED NOT NULL,
phase CHAR(5),
day SMALLINT UNSIGNED,
successful BIT,
roleset_id INT UNSIGNED,
datetime DATETIME,
PRIMARY KEY (kill_id) );

CREATE TABLE Guilts(
p_id INT UNSIGNED NOT NULL,
kill_id INT UNSIGNED NOT NULL,
PRIMARY KEY (p_id, kill_id) );
